/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package socialnetwork;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


@SpringBootApplication // @Configuration  @EnableAutoConfiguration   @ComponentScan
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

        SpringApplication.run(App.class, args);    
    }
}
