/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package socialnetwork;

import org.junit.jupiter.api.Test;


import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        // Arrange
        App classUnderTest = new App();

        // Act
        String greeting = classUnderTest.getGreeting();

        // Assert
        assertNotNull(greeting, "app should have a greeting");
    }
}
